# Generated by Django 6.0.1 on 2026-01-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaVacacionesADIP', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='celula',
            constraint=models.UniqueConstraint(fields=('nombre', 'area'), name='unique_celula_por_area'),
        ),
    ]
